# Woodpecker CI configuration file for Docusaurus blog
# Learn more at https://woodpecker-ci.org/docs/intro

pipeline:
  # Install dependencies
  deps:
    image: node:20-alpine
    commands:
      - npm install -g pnpm
      - pnpm install --registry https://registry.npmmirror.com
      - pnpm install --frozen-lockfile

  # Build the Docusaurus website
  build:
    image: node:20-alpine
    commands:
      - npm install -g pnpm
      - pnpm run build

  # 移动文件到临时目录
  transfer:
    image: appleboy/drone-scp
    settings:
      host: zhaogl.top
      port: 22
      username: zhaogl
      password: ${NAS_SSH_PASSWORD}
      source: build/
      target: /tmp/zgl-blog-dist/

  # Move files to target directory with sudo
  deploy:
    image: appleboy/drone-ssh
    settings:
      host: zhaogl.top
      port: 22
      username: zhaogl
      password: ${NAS_SSH_PASSWORD}
      script:
        - sudo mv /tmp/zgl-blog-dist/* /share/Web/zgl-blog/dist/
        - sudo chown -R www-data:www-data /share/Web/zgl-blog/dist/
        - rm -rf /tmp/zgl-blog-dist

branches: main