# Woodpecker CI configuration file for Docusaurus blog
# Learn more at https://woodpecker-ci.org/docs/intro

pipeline:
  # Install dependencies
  deps:
    image: node:20-alpine
    commands:
      - npm install -g pnpm
      - pnpm install --registry https://registry.npmmirror.com
      - pnpm install --frozen-lockfile

  # Build the Docusaurus website
  build:
    image: node:20-alpine
    commands:
      - npm install -g pnpm
      - pnpm run build

  # Deploy the Docusaurus website to the NAS
  deploy:
    image: appleboy/drone-scp
    settings:
      host: zhaogl.top
      port: 22
      username: zhaogl
      password: Zgl101756...
      source: build/
      target: /volume1/web/app/zgl-blog
      verbose: true

branches: main