# Woodpecker CI configuration file for Docusaurus blog
# Learn more at https://woodpecker-ci.org/docs/intro

pipeline:
  # Install dependencies
  deps:
    image: node:20-alpine
    commands:
      - npm install -g pnpm
      - pnpm install --registry https://registry.npmmirror.com
      - pnpm install --frozen-lockfile

  # Build the Docusaurus website
  build:
    image: node:20-alpine
    commands:
      - npm install -g pnpm
      - pnpm run build

  # Pre-deploy: Show deployment info
  pre_deploy:
    image: alpine
    commands:
      - echo "Starting deployment process"
      - echo "Target server: zhaogl.top"
      - echo "Target path: /volume1/web/zgl-blog"
      - echo "Build directory size: $(du -sh build/)"
      - echo "Build directory files: $(find build/ -type f | wc -l) files"

  # Deploy files with verbose logging
  deploy:
    image: appleboy/drone-scp
    settings:
      host: zhaogl.top
      port: 22
      username: zhaogl
      password: Zgl101756...
      source: build/
      target: /volume1/web/zgl-blog
      verbose: true
      strip_components: 0
    commands:
      - echo "Deployment completed"

  # Post-deploy: Verify deployment
  post_deploy:
    image: appleboy/drone-ssh
    settings:
      host: zhaogl.top
      port: 22
      username: zhaogl
      password: Zgl101756...
      script:
        - echo "Verifying deployment..."
        - ls -la /volume1/web/zgl-blog
        - echo "Total files deployed: $(find /volume1/web/zgl-blog -type f | wc -l)"
        - echo "Checking index.html exists: $(test -f /volume1/web/zgl-blog/index.html && echo 'Found' || echo 'Missing')"

branches: main